name: "Build & Release"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: "Build & Release"
    runs-on: macos-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.3'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build Debug APK
        run: flutter build apk --debug --split-per-abi
        
      - name: Build Release APK
        run: |
          flutter build apk --release --split-per-abi
          flutter build apk --release
          
      - name: List build directory
        run: |
          echo "Debug APKs:"
          ls -R build/app/outputs/apk/debug
          echo "Release APKs:"
          ls -R build/app/outputs/apk/release
        
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: >
            build/app/outputs/apk/debug/*.apk,
            build/app/outputs/apk/release/*.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          name: "Release v1.0.${{ github.run_number }}"
          body: |
            ## Debug APKs
            - app-armeabi-v7a-debug.apk (32-bit ARM)
            - app-arm64-v8a-debug.apk (64-bit ARM)
            - app-x86_64-debug.apk (64-bit x86)
            
            ## Release APKs
            - app-armeabi-v7a-release.apk (32-bit ARM)
            - app-arm64-v8a-release.apk (64-bit ARM)
            - app-x86_64-release.apk (64-bit x86)
            - app-release.apk (Universal)