# on:
#   pull_request:
#     branches:
#       - master

#   push:
#     branches:
#       - master

# name: "Build & Release"
# jobs:
#   build:
#     name: "Build & Release"
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "17.x"
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: "stable"
#           flutter-version: "3.24.3"  # Or remove this line to always use the latest stable version
#       - run: flutter pub get
#       - run: flutter build apk --debug --split-per-abi
#       - name: Push to Releases
#         uses: "ncipollo/release-action@v1"
#         with:
#           artifacts: "build/app/outputs/apk/debug/*"
#           tag: v1.0.${{ github.run_number }}
#           token: ${{secrets.new_token_linux}}

name: "Build & Release"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: "Build & Release"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.3'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --debug --split-per-abi
        
      - name: List build directory
        run: ls -R build/app/outputs/apk/debug
        
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/app-armeabi-v7a-debug.apk,build/app/outputs/apk/debug/app-arm64-v8a-debug.apk,build/app/outputs/apk/debug/app-x86_64-debug.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.new_token_linux }}
          generateReleaseNotes: true